### ISSUE TITLE
Moonlight II feat. optional GLOW™

### ISSUE THREAD

**Issue by atomiks** [atomiks/moonlight-vscode-theme#6]
### Inspired by the Synthwave84 theme:

![glowy moonlight ii](https://i.imgur.com/ahhJNj9.jpg)

I've been using it for a few hours and really like the subtle glows in certain places. You can [follow the steps outlined in his theme readme](https://github.com/robb0wen/synthwave-vscode#to-enable-the-glow)

Currently only cyan punctuation + purple keywords:

```css
.mtk5 {
  color: #93e2ff;
  text-shadow: 0 0 2px #000, 0 0 14px #46e3ff;
}

.mtk8 {
  color: #d0aeff;
  text-shadow: 0 0 2px #000, 0 0 10px #9a57ff, 0 0 35px #bf4fffbb;
}
```

Plenty of other tokens to add glow to if you want 👍 

Is this something you like? I can add it to the README and make it the default preview pic.

---

There's also a few color changes that I've made that I haven't released yet:

- Function calls and function definition colors are different (dark blue vs sky blue)
- Lighter bracket punctuation
- Objects (first-level) are yellow
